FROM node:22-alpine AS base

# =============================================
# STAGE 1: Install dependencies
# =============================================
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# =============================================
# STAGE 2: Build
# =============================================
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time environment variables (passed from Coolify)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_SUPABASE_ORDERS_URL
ARG NEXT_PUBLIC_SUPABASE_ORDERS_ANON_KEY
ARG GROQ_API_KEY
ARG CLOUDFLARE_R2_ACCOUNT_ID
ARG NEXT_PUBLIC_CLOUDFLARE_R2_ACCOUNT_ID
ARG CLOUDFLARE_R2_ACCESS_KEY_ID
ARG NEXT_PUBLIC_CLOUDFLARE_R2_ACCESS_KEY_ID
ARG CLOUDFLARE_R2_SECRET_ACCESS_KEY
ARG NEXT_PUBLIC_CLOUDFLARE_R2_SECRET_ACCESS_KEY
ARG CLOUDFLARE_R2_BUCKET_NAME
ARG NEXT_PUBLIC_CLOUDFLARE_R2_BUCKET_NAME
ARG CLOUDFLARE_R2_PUBLIC_URL
ARG NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL

# Set them as ENV so Next.js can see NEXT_PUBLIC_ vars at build time
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXT_PUBLIC_SUPABASE_ORDERS_URL=$NEXT_PUBLIC_SUPABASE_ORDERS_URL
ENV NEXT_PUBLIC_SUPABASE_ORDERS_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ORDERS_ANON_KEY
ENV GROQ_API_KEY=$GROQ_API_KEY
ENV CLOUDFLARE_R2_ACCOUNT_ID=$CLOUDFLARE_R2_ACCOUNT_ID
ENV NEXT_PUBLIC_CLOUDFLARE_R2_ACCOUNT_ID=$NEXT_PUBLIC_CLOUDFLARE_R2_ACCOUNT_ID
ENV CLOUDFLARE_R2_ACCESS_KEY_ID=$CLOUDFLARE_R2_ACCESS_KEY_ID
ENV NEXT_PUBLIC_CLOUDFLARE_R2_ACCESS_KEY_ID=$NEXT_PUBLIC_CLOUDFLARE_R2_ACCESS_KEY_ID
ENV CLOUDFLARE_R2_SECRET_ACCESS_KEY=$CLOUDFLARE_R2_SECRET_ACCESS_KEY
ENV NEXT_PUBLIC_CLOUDFLARE_R2_SECRET_ACCESS_KEY=$NEXT_PUBLIC_CLOUDFLARE_R2_SECRET_ACCESS_KEY
ENV CLOUDFLARE_R2_BUCKET_NAME=$CLOUDFLARE_R2_BUCKET_NAME
ENV NEXT_PUBLIC_CLOUDFLARE_R2_BUCKET_NAME=$NEXT_PUBLIC_CLOUDFLARE_R2_BUCKET_NAME
ENV CLOUDFLARE_R2_PUBLIC_URL=$CLOUDFLARE_R2_PUBLIC_URL
ENV NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL=$NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# =============================================
# STAGE 3: Production runner
# =============================================
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy public assets
COPY --from=builder /app/public ./public

# Copy standalone output
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
